app:
  velocity:
    templates:
      location: /templates/
spring:
  datasource:
    url: jdbc:postgresql://localhost/waviot_tasks
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        id:
          new_generator_mappings: false
server:
   port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 1 hour